application:
  name: goalservice
  message: Configured by Azure Spring Cloud
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://goals-microservice-db.mysql.database.azure.com:3306/goals
    username: spring
    password: GoalsAdmin123!
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
      show-sql: false
  jms:
    servicebus:
      connection-string: Endpoint=sb://goalsservice.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=WSJdd5dkKAAs2SKz6qpaD4WlLbr2ssOpx+ASbP9dDdA=
      pricing-tier: standard
      topic-client-id: 6ea22758-6c80-4841-88dc-182bf540d7e0
