application:
  name: userservice
  message: Configured by Azure Spring Cloud
spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
  jms:
    servicebus:
      connection-string: Endpoint=sb://goalsservice.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=WSJdd5dkKAAs2SKz6qpaD4WlLbr2ssOpx+ASbP9dDdA=
      pricing-tier: standard
      topic-client-id: 6ea22758-6c80-4841-88dc-182bf540d7e0
