application:
  name: userservice
  message: Configured by Azure Spring Cloud
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://user-microservice-db.mysql.database.azure.com:3306/items
    username: spring
    password: UserAdmin123!
  jpa:
    properties:
      hibernate:
        show_sql: false
    hibernate:
      ddl-auto: none
  jms:
    servicebus:
      connection-string: Endpoint=sb://goalsservice.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=WSJdd5dkKAAs2SKz6qpaD4WlLbr2ssOpx+ASbP9dDdA=
      pricing-tier: standard
      topic-client-id: 6ea22758-6c80-4841-88dc-182bf540d7e0
